"""Add timestamps and soft delete to Event model

Revision ID: 06751e050f5c
Revises: a2d45861f096
Create Date: 2025-06-05 16:14:04.597110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06751e050f5c'
down_revision = 'a2d45861f096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('event', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('event', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'deleted_at')
    op.drop_column('event', 'updated_at')
    op.drop_column('event', 'created_at')
    # ### end Alembic commands ###
