"""added field in user model

Revision ID: a2d45861f096
Revises: d129b369cadd
Create Date: 2025-06-03 16:28:59.718484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d45861f096'
down_revision = 'd129b369cadd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pending_organizer_approval', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pending_organizer_approval')
    # ### end Alembic commands ###
